export const currencies = [
  { code: "AED", flag: "ae", isSelected: false },
  { code: "AUD", flag: "au", isSelected: false },
  { code: "BDT", flag: "bd", isSelected: false },
  { code: "BHD", flag: "bh", isSelected: false },
  { code: "BND", flag: "bn", isSelected: false },
  { code: "BRL", flag: "br", isSelected: false },
  { code: "CAD", flag: "ca", isSelected: false },
  { code: "CHF", flag: "ch", isSelected: false },
  { code: "CLP", flag: "cl", isSelected: false },
  { code: "CNY", flag: "cn", isSelected: false },
  { code: "COP", flag: "co", isSelected: false },
  { code: "CZK", flag: "cz", isSelected: false },
  { code: "DKK", flag: "dk", isSelected: false },
  { code: "DZD", flag: "dz", isSelected: false },
  { code: "EGP", flag: "eg", isSelected: false },
  { code: "ETB", flag: "et", isSelected: false },
  { code: "EUR", flag: "eu", isSelected: false },
  { code: "FJD", flag: "fj", isSelected: false },
  { code: "GBP", flag: "gb", isSelected: false },
  { code: "HKD", flag: "hk", isSelected: false },
  { code: "HUF", flag: "hu", isSelected: false },
  { code: "IDR", flag: "id", isSelected: false },
  { code: "ILS", flag: "il", isSelected: false },
  { code: "INR", flag: "in", isSelected: false },
  { code: "JOD", flag: "jo", isSelected: false },
  { code: "JPY", flag: "jp", isSelected: false },
  { code: "KES", flag: "ke", isSelected: false },
  { code: "KHR", flag: "kh", isSelected: false },
  { code: "KRW", flag: "kr", isSelected: false },
  { code: "KWD", flag: "kw", isSelected: false },
  { code: "KZT", flag: "kz", isSelected: false },
  { code: "LKR", flag: "lk", isSelected: false },
  { code: "LYD", flag: "ly", isSelected: false },
  { code: "MMK", flag: "mm", isSelected: false },
  { code: "MNT", flag: "mn", isSelected: false },
  { code: "MOP", flag: "mo", isSelected: false },
  { code: "MXN", flag: "mx", isSelected: false },
  { code: "MYR", flag: "my", isSelected: false },
  { code: "NOK", flag: "no", isSelected: false },
  { code: "NPR", flag: "np", isSelected: false },
  { code: "NZD", flag: "nz", isSelected: false },
  { code: "OMR", flag: "om", isSelected: false },
  { code: "PHP", flag: "ph", isSelected: false },
  { code: "PKR", flag: "pk", isSelected: false },
  { code: "PLN", flag: "pl", isSelected: false },
  { code: "QAR", flag: "qa", isSelected: false },
  { code: "RON", flag: "ro", isSelected: false },
  { code: "RUB", flag: "ru", isSelected: false },
  { code: "SAR", flag: "sa", isSelected: false },
  { code: "SEK", flag: "se", isSelected: false },
  { code: "SGD", flag: "sg", isSelected: false },
  { code: "THB", flag: "th", isSelected: false },
  { code: "TRY", flag: "tr", isSelected: false },
  { code: "TWD", flag: "tw", isSelected: false },
  { code: "TZS", flag: "tz", isSelected: false },
  { code: "USD", flag: "us", isSelected: false },
  { code: "UZS", flag: "uz", isSelected: false },
  { code: "VND", flag: "vn", isSelected: false },
  { code: "ZAR", flag: "za", isSelected: false },
];

export const flagToCode = {
  ae: "AED",
  au: "AUD",
  bd: "BDT",
  bh: "BHD",
  bn: "BND",
  br: "BRL",
  ca: "CAD",
  ch: "CHF",
  cl: "CLP",
  cn: "CNY",
  co: "COP",
  cz: "CZK",
  dk: "DKK",
  dz: "DZD",
  eg: "EGP",
  et: "ETB",
  eu: "EUR",
  fj: "FJD",
  gb: "GBP",
  hk: "HKD",
  hu: "HUF",
  id: "IDR",
  il: "ILS",
  in: "INR",
  jo: "JOD",
  jp: "JPY",
  ke: "KES",
  kh: "KHR",
  kr: "KRW",
  kw: "KWD",
  kz: "KZT",
  lk: "LKR",
  ly: "LYD",
  mm: "MMK",
  mn: "MNT",
  mo: "MOP",
  mx: "MXN",
  my: "MYR",
  no: "NOK",
  np: "NPR",
  nz: "NZD",
  om: "OMR",
  ph: "PHP",
  pk: "PKR",
  pl: "PLN",
  qa: "QAR",
  ro: "RON",
  ru: "RUB",
  sa: "SAR",
  se: "SEK",
  sg: "SGD",
  th: "THB",
  tr: "TRY",
  tw: "TWD",
  tz: "TZS",
  us: "USD",
  uz: "UZS",
  vn: "VND",
  za: "ZAR",
};

export const flagImageMap = {
  ae: require("@/assets/images/ae.png"),
  au: require("@/assets/images/au.png"),
  bd: require("@/assets/images/bd.png"),
  bh: require("@/assets/images/bh.png"),
  bn: require("@/assets/images/bn.png"),
  br: require("@/assets/images/br.png"),
  ca: require("@/assets/images/ca.png"),
  ch: require("@/assets/images/ch.png"),
  cl: require("@/assets/images/cl.png"),
  cn: require("@/assets/images/cn.png"),
  co: require("@/assets/images/co.png"),
  cz: require("@/assets/images/cz.png"),
  dk: require("@/assets/images/dk.png"),
  dz: require("@/assets/images/dz.png"),
  eg: require("@/assets/images/eg.png"),
  et: require("@/assets/images/et.png"),
  eu: require("@/assets/images/eu.png"),
  fj: require("@/assets/images/fj.png"),
  gb: require("@/assets/images/gb.png"),
  hk: require("@/assets/images/hk.png"),
  hu: require("@/assets/images/hu.png"),
  id: require("@/assets/images/id.png"),
  il: require("@/assets/images/il.png"),
  in: require("@/assets/images/in.png"),
  jo: require("@/assets/images/jo.png"),
  jp: require("@/assets/images/jp.png"),
  ke: require("@/assets/images/ke.png"),
  kh: require("@/assets/images/kh.png"),
  kr: require("@/assets/images/kr.png"),
  kw: require("@/assets/images/kw.png"),
  kz: require("@/assets/images/kz.png"),
  lk: require("@/assets/images/lk.png"),
  ly: require("@/assets/images/ly.png"),
  mm: require("@/assets/images/mm.png"),
  mn: require("@/assets/images/mn.png"),
  mo: require("@/assets/images/mo.png"),
  mx: require("@/assets/images/mx.png"),
  my: require("@/assets/images/my.png"),
  no: require("@/assets/images/no.png"),
  np: require("@/assets/images/np.png"),
  nz: require("@/assets/images/nz.png"),
  om: require("@/assets/images/om.png"),
  ph: require("@/assets/images/ph.png"),
  pk: require("@/assets/images/pk.png"),
  pl: require("@/assets/images/pl.png"),
  qa: require("@/assets/images/qa.png"),
  ro: require("@/assets/images/ro.png"),
  ru: require("@/assets/images/ru.png"),
  sa: require("@/assets/images/sa.png"),
  se: require("@/assets/images/se.png"),
  sg: require("@/assets/images/sg.png"),
  th: require("@/assets/images/th.png"),
  tr: require("@/assets/images/tr.png"),
  tw: require("@/assets/images/tw.png"),
  tz: require("@/assets/images/tz.png"),
  us: require("@/assets/images/us.png"),
  uz: require("@/assets/images/uz.png"),
  vn: require("@/assets/images/vn.png"),
  za: require("@/assets/images/za.png"),
};
